language: node_js
node_js:
  - "stable"

jobs:
  include:
    - stage: deploy
      node_js: "stable"
      script:
        - npm run build

      deploy:
        provider: pages
        local_dir: build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          tags: true
