language: node_js
node_js:
  - "stable"

jobs:
  include:
    - stage: npm release
      node_js: "stable"
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: vs@lutov.net
        on:
          tags: true

    - stage: deploy
      node_js: "stable"
      script:
        - npm run build

      deploy:
        provider: pages
        local_dir: build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          tags: true
